# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18HcASWka20PnAYsvFjSXZNauK2srpNbn
"""

import sys, os, argparse, time
import numpy as np

try:
    _root = os.path.dirname(os.path.abspath(__file__))
except NameError:
    _root = "/content/Trupal_capstone_project"

if _root not in sys.path:
    sys.path.insert(0, _root)
os.chdir(_root)

from envs.gridworld           import GridWorld
from agents.q_learning         import QLearningAgent
from agents.sarsa              import SARSAAgent
from agents.double_q_learning  import DoubleQLearningAgent
from experiments.train         import (train, run_multiple_seeds,
                                       policy_stability, convergence_episode)
from experiments.visualize     import (plot_gridworld, plot_qlearning_baseline,
                                       plot_learning_curves, plot_convergence,
                                       plot_policies, plot_value_heatmaps,
                                       plot_overestimation_bias, plot_steps,
                                       plot_multiseed, plot_hyperparam_sensitivity,
                                       plot_metrics_table)


# parse_args
def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--episodes",       type=int,   default=2000)
    p.add_argument("--alpha",          type=float, default=0.1)
    p.add_argument("--gamma",          type=float, default=0.9)
    p.add_argument("--epsilon",        type=float, default=0.1)
    p.add_argument("--seed",           type=int,   default=42)
    p.add_argument("--results-dir",    type=str,   default="results")
    p.add_argument("--skip-sweep",     action="store_true")
    p.add_argument("--sweep-episodes", type=int,   default=1000)
    p.add_argument("--n-seeds",        type=int,   default=5)
    return p.parse_args()


# make_agents
def make_agents(alpha, gamma, epsilon, seed):
    return {
        "Q-Learning":        QLearningAgent(      alpha=alpha, gamma=gamma, epsilon=epsilon, seed=seed),
        "SARSA":             SARSAAgent(           alpha=alpha, gamma=gamma, epsilon=epsilon, seed=seed),
        "Double Q-Learning": DoubleQLearningAgent( alpha=alpha, gamma=gamma, epsilon=epsilon, seed=seed),
    }


# train_on_env
def train_on_env(agents, env_kwargs, n_episodes, verbose, seed):
    results = {}
    for name, agent in agents.items():
        env = GridWorld(**env_kwargs, seed=seed)
        print(f"  Training {name}...")
        m = train(agent, env, n_episodes=n_episodes, verbose=verbose)
        results[name] = {"agent": agent, "metrics": m}
    return results


# compute_metrics_row
def compute_metrics_row(name, env_label, data):
    m     = data["metrics"]
    avg_r = float(np.mean(m["rewards"][-100:]))
    avg_s = float(np.mean(m["steps"][-100:]))
    conv  = convergence_episode(m["max_delta_q"])
    stab  = policy_stability(m["max_delta_q"])
    return {
        "Algorithm":   name,
        "Environment": env_label,
        "AvgReward":   avg_r,
        "AvgSteps":    avg_s,
        "ConvEp":      conv,
        "PolicyStab":  stab,
        "QBias":       "ref" if name == "Q-Learning" else "n/a",
    }


# main
def main():
    args = parse_args()
    os.makedirs(args.results_dir, exist_ok=True)
    t0 = time.time()

    print(f"Config: episodes={args.episodes}, alpha={args.alpha}, gamma={args.gamma}, epsilon={args.epsilon}, seed={args.seed}")

    env_ref = GridWorld(stochastic=False, seed=args.seed)
    plot_gridworld(env_ref, args.results_dir)

    print("\nQ-learning baseline (deterministic):")
    env_m1 = GridWorld(stochastic=False, seed=args.seed)
    q_base = QLearningAgent(alpha=args.alpha, gamma=args.gamma, epsilon=args.epsilon, seed=args.seed)
    train(q_base, env_m1, n_episodes=args.episodes, verbose=True)
    plot_qlearning_baseline(q_base, args.results_dir)
    print("\nV(s) = max_a Q(s,a):")
    print(np.round(q_base.V, 3))
    print("\nLearned policy:")
    print(env_m1.render_ascii(q_base.Q))

    print("\nDeterministic environment:")
    agents_det  = make_agents(args.alpha, args.gamma, args.epsilon, args.seed)
    results_det = train_on_env(agents_det, {"stochastic": False}, args.episodes, True, args.seed)

    print("\nStochastic environment (p=0.8):")
    agents_sto  = make_agents(args.alpha, args.gamma, args.epsilon, args.seed)
    results_sto = train_on_env(agents_sto, {"stochastic": True, "slip_prob": 0.8}, args.episodes, True, args.seed)

    metrics_rows = []
    for env_label, results in [("Deterministic", results_det), ("Stochastic", results_sto)]:
        q_vals  = [np.max(results["Q-Learning"]["agent"].Q[r, c])
                   for r in range(5) for c in range(5) if env_ref.cell_type(r, c) != "wall"]
        dq_vals = [np.max(results["Double Q-Learning"]["agent"].Q[r, c])
                   for r in range(5) for c in range(5) if env_ref.cell_type(r, c) != "wall"]
        bias = float(np.mean(np.array(q_vals) - np.array(dq_vals)))
        for name, data in results.items():
            row = compute_metrics_row(name, env_label, data)
            if name == "Double Q-Learning":
                row["QBias"] = f"{bias:+.4f}"
            metrics_rows.append(row)

    print("\nGenerating plots...")
    plot_learning_curves(results_det, results_sto, args.results_dir)
    plot_convergence(results_det, results_sto, args.results_dir)
    plot_policies(results_det, results_sto, env_ref, args.results_dir)
    plot_value_heatmaps(results_det, results_sto, env_ref, args.results_dir)
    plot_overestimation_bias(results_det, results_sto, env_ref, args.results_dir)
    plot_steps(results_det, results_sto, args.results_dir)
    plot_metrics_table(metrics_rows, args.results_dir)

    print("\nEvaluation metrics (last 100 episodes):")
    print(f"  {'Algorithm':<22} {'Env':<15} {'AvgReward':>10} {'AvgSteps':>9} {'ConvEp':>8} {'Stab':>6} {'QBias':>9}")
    print(f"  {'-'*22} {'-'*15} {'-'*10} {'-'*9} {'-'*8} {'-'*6} {'-'*9}")
    for row in metrics_rows:
        conv = str(row["ConvEp"]) if row["ConvEp"] >= 0 else "N/C"
        print(f"  {row['Algorithm']:<22} {row['Environment']:<15} "
              f"{row['AvgReward']:>10.4f} {row['AvgSteps']:>9.1f} "
              f"{conv:>8} {row['PolicyStab']:>6.2f} {row['QBias']:>9}")

    print(f"\nMulti-seed robustness ({args.n_seeds} seeds, deterministic):")
    base_kw    = dict(alpha=args.alpha, gamma=args.gamma, epsilon=args.epsilon)
    ms_results = {}
    for name, Cls in [("Q-Learning", QLearningAgent),
                      ("SARSA", SARSAAgent),
                      ("Double Q-Learning", DoubleQLearningAgent)]:
        ms_results[name] = run_multiple_seeds(Cls, base_kw, {"stochastic": False},
                                               n_episodes=args.episodes, n_seeds=args.n_seeds)
        avg = ms_results[name]["rewards_mean"][-100:].mean()
        std = ms_results[name]["rewards_std"][-100:].mean()
        print(f"  {name:<22}: {avg:.4f} +/- {std:.4f}")
    plot_multiseed(ms_results, args.results_dir)

    if not args.skip_sweep:
        print("\nHyperparameter sweep...")
        alphas   = [0.01, 0.05, 0.1, 0.2, 0.3, 0.5]
        epsilons = [0.01, 0.05, 0.1, 0.2, 0.3, 0.5]
        for idx, (pname, pvals, fixed) in enumerate([
            ("alpha",   alphas,   {"epsilon": 0.1}),
            ("epsilon", epsilons, {"alpha":   0.1}),
        ]):
            scores = {n: [] for n in ["Q-Learning", "SARSA", "Double Q-Learning"]}
            for val in pvals:
                for name, Cls in [("Q-Learning", QLearningAgent),
                                   ("SARSA", SARSAAgent),
                                   ("Double Q-Learning", DoubleQLearningAgent)]:
                    kw = {**base_kw, **fixed, "seed": args.seed, pname: val}
                    m  = train(Cls(**kw), GridWorld(stochastic=False, seed=args.seed),
                               n_episodes=args.sweep_episodes)
                    scores[name].append(float(np.mean(m["rewards"][-100:])))
                print(f"  {pname}={val:.2f}: " + "  ".join(f"{n[:2]}={scores[n][-1]:.2f}" for n in scores))
            plot_hyperparam_sensitivity(pname, pvals, scores, args.results_dir, idx)

    print(f"\nDone in {time.time()-t0:.1f}s  |  Results saved to: {args.results_dir}/")


if __name__ == "__main__":
    main()